'use client';

import { AlertTriangle } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen pt-20 pb-12">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 pt-8">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-[#8A2BE2]/10 border border-[#8A2BE2]/20 mb-5">
            <AlertTriangle className="h-7 w-7 text-[#8A2BE2]" />
          </div>
          <h1 className="text-3xl sm:text-5xl font-black text-white mb-4 tracking-tight">
            <span className="gradient-text">Disclaimer</span>
          </h1>
          <p className="text-[#AAAAAA] text-sm">Last updated: May 29, 2026</p>
        </div>

        <div className="bg-[#111111] border border-[#1a1a1a] rounded-2xl p-6 sm:p-8 space-y-8">
          {/* General Disclaimer */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">General Disclaimer</h2>
            <p className="text-[#AAAAAA] leading-relaxed text-sm">
              The information provided by ToolBox Pro (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) on toolboxpro.com (the &quot;Site&quot;) is for general informational purposes only. All information on the Site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site. Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Site or reliance on any information provided on the Site. Your use of the Site and your reliance on any information on the Site is solely at your own risk.
            </p>
          </section>

          {/* Tool Results */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">Tool Results Disclaimer</h2>
            <p className="text-[#AAAAAA] leading-relaxed text-sm">
              The tools provided on ToolBox Pro are intended for general informational and utility purposes only. While we strive for accuracy, we do not guarantee that the results produced by our tools will be error-free or suitable for any particular purpose. Passwords generated by our Password Generator tool are created using cryptographically secure random number generation, but we recommend using a dedicated password manager for storing sensitive credentials. Image compression results may vary depending on the original image format and content. Users should always verify the output of any tool before using it for critical applications.
            </p>
          </section>

          {/* External Links */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">External Links Disclaimer</h2>
            <p className="text-[#AAAAAA] leading-relaxed text-sm">
              The Site may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the Site or any website or feature linked in any advertisement. We will not be a party to or in any way be responsible for monitoring any transaction between you and any third-party providers of products or services.
            </p>
          </section>

          {/* Affiliate Disclaimer */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">Affiliate Disclaimer</h2>
            <p className="text-[#AAAAAA] leading-relaxed text-sm">
              The Site may contain links to affiliate websites, and we receive an affiliate commission for any purchases made by you on the affiliate website using such links. Our affiliates include, but are not limited to, software companies, hosting providers, and online service providers. We only recommend products and services that we believe may be valuable to our users. The inclusion of affiliate links does not influence our recommendations or tool functionality. All of our tools remain completely free to use regardless of whether you purchase through our affiliate links.
            </p>
          </section>

          {/* Professional Advice */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">Professional Advice Disclaimer</h2>
            <p className="text-[#AAAAAA] leading-relaxed text-sm">
              The Site cannot and does not contain professional advice. The tools and information are provided for general informational and utility purposes only. They are not a substitute for professional advice. Accordingly, before taking any actions based upon such information, we encourage you to consult with the appropriate professionals. We do not provide any kind of professional advice. The use or reliance of any information contained on this Site is solely at your own risk.
            </p>
          </section>

          {/* YouTube and Instagram */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">Third-Party Platform Disclaimer</h2>
            <p className="text-[#AAAAAA] leading-relaxed text-sm">
              ToolBox Pro is not affiliated with, endorsed by, or officially connected with YouTube, Instagram, or any other third-party platform. The YouTube Thumbnail Downloader tool allows users to download publicly available thumbnail images from YouTube videos. The Instagram Reel Downloader tool allows users to download publicly available reel content. Users are solely responsible for ensuring that their use of downloaded content complies with the respective platform&apos;s terms of service and applicable copyright laws. We do not encourage or condone the unauthorized downloading or distribution of copyrighted content.
            </p>
          </section>

          {/* Consent */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">Consent</h2>
            <p className="text-[#AAAAAA] leading-relaxed text-sm">
              By using our website, you hereby consent to our Disclaimer and agree to its terms. If you have any questions about this Disclaimer, please contact us at: <strong className="text-white">hello@toolboxpro.com</strong>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
